### ISSUE TITLE
Incorrect Daniel Rosenwasser code sample URL

### ISSUE THREAD

**Issue by benglynn** [AndreasIllg/ngEurope2016-resources#1]
It should be: https://github.com/DanielRosenwasser/ng-conf-2016

**Comment by AndreasIllg** [comment]
At the end of his talk yesterday, he said he will upload this in the evening or at night, so I included the url he mentioned. But he obviously hasn't (yet). So I took out the link.
The link you suggested was the stuff from his talk at ng-conf in Salt Lake City this year (Latest commit on 6 May).
(see also: https://github.com/AndreasIllg/ngconf2016-slides/blob/master/ngconf-slides.md)

**Comment by benglynn** [comment]
Thanks Andreas.

**Comment by AndreasIllg** [comment]
Thanks for testing out the links, but Daniel also had a talk at ng-conf 
in Salt Lake City this year.

And this was his stuff from there (Latest commit on 6 May)

(see: 
https://github.com/AndreasIllg/ngconf2016-slides/blob/master/ngconf-slides.md)

At the end of his talk yesterday, he promised to load this up in the 
evening or at night, so I included the url he mentioned. But he 
obviously hasn't.

I will take it out when I update the repo today.

Andreas
